#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const {validatePack}=require('../site/js/engine.js');
const {validateEvidence}=require('./review-evidence.cjs');
const root=path.resolve(__dirname,'..');
let bank=JSON.parse(fs.readFileSync(path.join(root,'content/core.json'),'utf8'));
let errors=validatePack(bank);
if(errors.length){console.error(errors.join('\n'));process.exit(1);}
const audit=JSON.parse(fs.readFileSync(path.join(root,'docs/CONTENT_AUDIT.json'),'utf8'));
const extras=fs.readdirSync(path.join(root,'content/packs')).filter(f=>f.endsWith('.json')).sort();
for(const file of extras){
 const p=JSON.parse(fs.readFileSync(path.join(root,'content/packs',file),'utf8'));
 errors=validatePack(p,bank);if(errors.length){console.error(file,errors);process.exit(1);}
 Object.assign(bank.sources,p.sources);bank.concepts.push(...p.concepts);bank.questions.push(...p.questions);
}
for(const q of bank.questions)if(q.asset&&!fs.existsSync(path.join(root,'site',q.asset))){console.error('Missing asset',q.asset);process.exit(1);}
errors=validateEvidence(bank,audit,root);
if(errors.length){console.error(errors.join('\n'));process.exit(1);}
const stats={concepts:bank.concepts.length,questions:bank.questions.length,sourceCheckedQuestions:bank.questions.filter(q=>(q.reviewStatus||bank.concepts.find(c=>c.id===q.concept).reviewStatus)==='source-checked').length};
bank.buildStats=stats;
const js='/* Generated from content/core.json and content/packs/*.json. Run npm run build. */\nwindow.ROAD_READY_BANK = '+JSON.stringify(bank,null,0).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')+';\n';
const dest=path.join(root,'site/js/bank.js');
if(process.argv.includes('--check')){
 if(!fs.existsSync(dest)||fs.readFileSync(dest,'utf8')!==js){console.error('Compiled bank is stale. Run npm run build.');process.exit(1);}
}else{
 fs.writeFileSync(dest,js);
 const lines=['# Question source-review inventory','','Generated by `npm run build`. Editorial findings are preserved separately in [CONTENT_AUDIT.md](CONTENT_AUDIT.md); document identity and limits are in [SOURCES.md](SOURCES.md). “Source checked” means reviewed against the identified official document, not certified as current law. Imported questions remain pending until separately reviewed.','',`${stats.sourceCheckedQuestions} of ${stats.questions} questions are source checked; ${stats.questions-stats.sourceCheckedQuestions} remain pending.`,'','| Rule | Topic | Variants | Checked / pending | PDF page | Source section |','|---|---|---:|---|---|---|'];
 for(const c of bank.concepts){
  const qs=bank.questions.filter(q=>q.concept===c.id),checked=qs.filter(q=>(q.reviewStatus||c.reviewStatus)==='source-checked').length;
  const page=c.pdfPage?`[${c.pdfPage}](${bank.sources[c.sourceId].url}#page=${c.pdfPage})`:'—';
  lines.push(`| ${c.id} | ${c.topic} | ${qs.length} | ${checked} / ${qs.length-checked} | ${page} | ${c.section} |`);
 }
 fs.writeFileSync(path.join(root,'docs/CONTENT_REVIEW.md'),lines.join('\n')+'\n');
}
console.log(`Bank: ${stats.questions} question variants / ${stats.concepts} rule families / ${stats.sourceCheckedQuestions} source-checked questions. ${stats.questions-stats.sourceCheckedQuestions} require source review.`);
